bug-fixes and stability fixes

diff --git a/community.sap_install/bin/sap_hana_preconfigure b/community.sap_install/bin/sap_hana_preconfigure
--- a/community.sap_install/bin/sap_hana_preconfigure
+++ b/community.sap_install/bin/sap_hana_preconfigure
@@ -2,6 +2,21 @@
 
 # Call this script interactively to prepare your system(s) for a SAP HANA installation
 
+# run a cleanup, if program ends unexpected
+trap cleanup INT
+
+function cleanup() {
+  # reset font color
+  printf '\033[m'
+  
+  # remove temporary files
+  if [ -f $"{params}" ]; then
+    [[ '[yY]' =~ $(ask "Do you want to remove the configfile ${params}? (y/n)" "n" "^[yYnN]$") ]] && rm -f ${params} || echo "keeping config file"
+  fi
+  
+  exit 1
+}
+
 info() {
 cat << EOT
 *****************************************************************************
@@ -19,7 +34,7 @@ EOT
 
 usage() {
 cat << EOT
-Call $(basename $0) [-h] [-i inventory] [-p parameterfile] [-v path_to_python_venv] [-n] [-u user] [-k] [-K] [font_light_gray|font_no_color] [reset]
+Call $(basename $0) [-h] [-i inventory] [-p parameterfile] [-v path_to_python_venv] [-n] [-u user] [-k] [-K] [-c font_light_gray|font_no_color]
 Optional Parameters 
 
 -h : help 
@@ -30,8 +45,7 @@ Optional Parameters
 -u : connection user
 -k : connection password
 -K : BECOME password
-font_light_grey|font_no_color: Set readable font color
-reset: reset font color
+-c : font_light_grey|font_no_color: Set standard font color for assert output
 
 EOT
 }
@@ -99,8 +113,12 @@ info
 
 ##  Check if an ansible inventory is given on the command line
 extra_args=""
+# default font color: Light Cyan, which should be readable on both bright and dark background
+# Needed for assert only
+#__FONT_COLOR=36m
+__FONT_COLOR=m # regular color
 
-while getopts ':hi:p:v:nkKu:' OPTION; do
+while getopts ':hi:p:v:nkKu:c:' OPTION; do
   case "${OPTION}" in
     h) 
       # help message
@@ -127,7 +145,7 @@ while getopts ':hi:p:v:nkKu:' OPTION; do
          echo "Creating Ansible Installation in Python Virtual Environment"
 	      python3 -m venv ${venv}
          . ${venv}/bin/activate
-         pip install ansible
+         pip install ansible==9.6.1 # defined version for environment
       fi
       ;;
 
@@ -151,6 +169,15 @@ while getopts ':hi:p:v:nkKu:' OPTION; do
       extra_args+=" -u ${OPTARG}"
       ;;
 
+    c)
+      # Set default font color
+      if [[ "${OPTARG}" == "font_light_gray" ]]; then
+        __FONT_COLOR=37m
+      elif [[ "${OPTARG}" == "font_no_color" ]]; then
+        __FONT_COLOR=30m
+      fi
+      ;;
+     
     ?) 
       # Catch all rule
       usage
@@ -163,19 +190,13 @@ done
 # if other parameters are added in the future
 shift "$(($OPTIND -1))"
 
-# default font color: Light Cyan, which should be readable on both bright and dark background
-__FONT_COLOR=36m
-
-if [[ ${1}. == "font_light_gray". ]]; then
-   __FONT_COLOR=37m
-elif [[ ${1}. == "font_no_color". ]]; then
-   __FONT_COLOR=30m
-fi
-
-if [[ ${2}. == "reset." ]]; then
-   awk 'BEGIN{printf ("\033['${__FONT_COLOR}'Resetting font color\n")}'
-   exit
-fi
+# Set default font color
+printf "\033[${__FONT_COLOR}"
+# Should not be necessary
+#if [[ ${2}. == "reset." ]]; then
+#   awk 'BEGIN{printf ("\033['${__FONT_COLOR}'Resetting font color\n")}'
+#   exit
+#fi
 
 ## Check if inventory file or implicit inventory declaration is used
 if [ -n "${inventory}" ]; then
@@ -247,9 +268,9 @@ else
   echo "running the playbook"
   echo "ansible-playbook ${ap_parameter} ${extra_args} community.sap_install.sap_hana_preconfigure_exec.yml -e @${params}"
   if [ "${assert}" == "false" ]; then
-     ansible-playbook ${ap_parameter} ${extra_args} community.sap_install.sap_hana_preconfigure_exec.yml -e @${params}
+     LANG=en_US.UTF-8 ansible-playbook ${ap_parameter} ${extra_args} community.sap_install.sap_hana_preconfigure_exec.yml -e @${params}
   else # assert = true
-    ansible-playbook ${ap_parameter} ${extra_args} community.sap_install.sap_hana_preconfigure_exec.yml -e @${params} |\
+    LANG=en_US.UTF-8 ansible-playbook ${ap_parameter} ${extra_args} community.sap_install.sap_hana_preconfigure_exec.yml -e @${params} |\
     awk '{sub ("    \"msg\": ", "")}
       /TASK/{task_line=$0}
       /fatal:/{fatal_line=$0; nfatal[host]++}
@@ -269,5 +290,7 @@ else
         if (nfail[var] != 0) exit (nfail[var])
       }'
   fi
-  echo "You can store the config file ${params} for future use"
+  printf '\033[m' # restore color
+  echo ""
+  echo "You can copy the config file ${params} for future use"
 fi
